services:
  app:
    build: .
    container_name: app
    networks:
    - local
    ports:
      - "8080:8080"
    expose:
      - 8080
  redis:
    image: redis:7.2.1
    container_name: redis
    networks:
      - local
networks:
  local: